language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  # Update composer
  - composer self-update
  - composer install --dev
  # Install Nette Tester
  - travis_retry composer update --no-interaction --prefer-dist $dependencies

script: ./vendor/bin/tester -p php -c ./tests/php.ini-unix ./tests/

after_failure:
  # Print *.actual content
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

sudo: false