language: php

php:
  - 7.3
  - 7.4

before_script:
  # Update composer
  - composer self-update
  - composer install --dev
  # Install Nette Tester
  - travis_retry composer update --no-interaction --prefer-dist $dependencies

script: ./vendor/bin/tester -p php -c ./tests/php.ini-travis ./tests/

after_failure:
  # Print *.actual content
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

sudo: false
