name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4']
      fail-fast: false

    name: PHP ${{ matrix.php }} PHPStan
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - run: composer install --no-progress --prefer-dist
      - run: vendor/bin/phpstan

  phpstan-lowest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1']
      fail-fast: false

    name: PHP ${{ matrix.php }} PHPStan - lowest dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - run: composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable
      - run: vendor/bin/phpstan

