name: Tests

on: [push, pull_request]

env:
  php-options: -C -d opcache.enable=0 -d zend.exception_ignore_args=0

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4']
      fail-fast: false

    name: PHP ${{ matrix.php }} tests
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - run: composer install --no-progress --prefer-dist
      - run: vendor/bin/tester tests -p php -s ${{ env.php-options }}

  tests-lowest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1']
      fail-fast: false

    name: PHP ${{ matrix.php }} tests - lowest dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - run: composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable
      - run: vendor/bin/tester tests -p php -s ${{ env.php-options }}

